### ISSUE TITLE
Issue with typesetting of draft legislation

### ISSUE THREAD

**Issue by ajhaydock** [PaulStanley/oscola-biblatex#4] opened 2017-03-21 15:18 UTC
Thanks for your great work on this package! Noticed there was some activity on here recently and I hope I'm not too late to catch the v1.5 release with this issue if it does turn out to be a bug.

I have an issue that causes a strange typesetting on the word "bill" when citing draft legislation. It happens in both footnotes, and in tables at the end of the document.

![screenshot_2017-03-21_15-03-49](https://cloud.githubusercontent.com/assets/13152214/24153923/a365f20c-0e47-11e7-95e8-f79887ed7025.png)

For some reason, despite my use of "Bill" in the legislation's name no differently than when citing any other statute, it ends up typeset fully lowercase and in bold text. It also happens when omitting "Bill" entirely from the statute's `title` field.

As far as I can tell, this typesetting isn't a requirement in the OSCOLA guidelines and doesn't seem to match the example output [on page 47 of your documentation](http://mirror.ox.ac.uk/sites/ctan.org/macros/latex/contrib/biblatex-contrib/oscola/oscola.pdf).

I've put together a minimal working example that shows this in action. Hopefully you can replicate it, as I've experienced the issue using the `texlive-oscola` packages from the Fedora repositories, and also when manually installing the full TeX Live distribution [with their quick install guide](https://www.tug.org/texlive/quickinstall.html).

I don't think it's an issue with my TeX setup more generally, as everything else seems to work as expected (except the ibid punctuation issue, so thanks for the recent fix to that!).

I'll include a `.tex` and `.bib` example below that (hopefully) demonstrates the issue I'm having. You can see the PDF that the files produce when I process them [here](https://github.com/PaulStanley/oscola-biblatex/files/858593/test.pdf).

Thanks again for the work on this package and for any help you can provide!

-----------------------

##### `test.tex`
```tex
\documentclass[a4paper]{article}

% General Packages
\usepackage[english]{babel} % Provides language-specific ty­po­graph­i­cal (and other) rules
\usepackage[utf8]{inputenc} % Input encoding

% Load OSCOLA
\usepackage[style=oscola,backend=biber,indexing=cite]{biblatex}
\addbibresource{test.bib}
\usepackage[style=british]{csquotes}

% Setup Index
\usepackage[splitindex,nonewpage]{imakeidx}
\makeindex[name=pmats,intoc=true,title={UK Parliamentary Material and Draft Legislation},columns=1]
\DeclareIndexAssociation{gbdraftleg}{pmats}
\DeclareIndexAssociation{gbparltmat}{pmats}

% Document
\begin{document}

Lorem ipsum dolor sit amet, consectetur adipiscing elit.\autocite{DEBill}

In nec scelerisque nisl. Maecenas ac dictum tortor.\autocite{DEBill2}

\pagebreak
\printindex[pmats] % UK Parliamentary Material and Draft Legislation table

\end{document}
```

##### `test.bib`
```tex
@Legislation{DEBill,
  Title                    = {Digital Economy Bill},
  Date                     = {2016/2017},
  Institution              = {HL},
  Number                   = {102},
  Keywords                 = {gb, draft},
  Entrysubtype             = {primary},
  Pagination               = {clause},
}

@Legislation{DEBill2,
  Title                    = {Digital Economy},
  Date                     = {2016/2017},
  Institution              = {HL},
  Number                   = {102},
  Keywords                 = {gb, draft},
  Entrysubtype             = {primary},
  Pagination               = {clause},
}
```

**Comment by PaulStanley** [comment] 2017-03-25 15:23
Thanks for this. I am afraid (my fault not yours!) that I missed this and have just submitted 1.5 to CTAN! But I can always amend later. It looks to me as if I have forgotten to define a bibliography string for bill, which is why it is printing that way. Definitely a bug. Thanks for spotting it.

**Comment by PaulStanley** [comment] 2017-03-27 11:23
This is the result of what (continues to be) a bug in the way we are handling language definition files, which has been hard to work out. I *think* I have now solved it. The workaround for the moment is to select `british` rather than `english` as your Babel language. The alternative is to edit the file `english-oscola.lbx` so that it includes the line `InheritBibliographyExtras{english}` immediately after line 8.

Meanwhile I am happy (for some definition of happy!) to say that your example also uncovered a spacing bug in draft legislation if you don't have a postnote (you will get an extra space before the full stop in a footnote. The correction for that is at line 1625 of `oscola.bbx`, where you need to delete the whole line, adding a closing brace at the end of the previous line.

I will commit corrections to this repo within 24 hours. Since I've just uploaded a revised version to CTAN, and that always risks producing new bugs anyway, I will probably wait to correct the CTAN version for a week or two.

FWIW, on Linux, I always recommend maintaining a "proper" TeXLive distribution, because it gets updated so much more quickly and effectively than packages, which have a bad history of lingering in what is (in bibliographical terms) the distant past. This has nothing to do with the error in this case, which was my fault, but if you are working on stuff that changes often it's worth bearing in mind.

**Closed by PaulStanley** 2017-03-27 11:23 UTC
Labels: bug

**Comment by ajhaydock** [comment] 2017-03-27 13:06
Thanks for the fixes!

> FWIW, on Linux, I always recommend maintaining a "proper" TeXLive distribution, because it gets updated so much more quickly and effectively than packages, which have a bad history of lingering in what is (in bibliographical terms) the distant past.

As for this, I'm mostly stuck doing this anyway, since it seems that the only distribution which actually appears to make the OSCOLA package available is Fedora. For whatever reason (I can't work it out, but would be interested to find out) it doesn't form part of the TeXLive package set available in Ubuntu/Debian or in CentOS/RHEL.

**Comment by PaulStanley** [comment] 2017-03-27 13:34
I'm (happily!) not a Linux distro maintainer, but I think the problem is that TeX is a very "big" system, and they tend to support only a minimal subset which will keep the most basic user happy. In practice it's not such a terrible thing, since TeXlive does a good job, IME. It may be that Debian also has trouble with some of the licensing, because CTAN contains some packages which are either not free or questionably free. I wasn't around for it, but I think there have been substantial licensing issues, and although most of what is in the tree (including I am happy to say OSCOLA) is properly free, not all of it is.
